# Generated by Django 4.2.7 on 2023-12-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.FileField(blank=True, help_text='Imagem do projeto', upload_to='imagens/', verbose_name='Imagem do projeo'),
        ),
    ]
